

# Multipliers

Christian Schoder

<cschoder@worldbank.org>

Remzi Barış Tercioğlu

<rtercioglu@worldbank.org>



## List of acronyms

**<span class="underline">Institutions</span>**

OECD Organisation for Economic Co-operation and Development

UNU WIDER World Institute for Development Economics Research

**<span class="underline">Abbreviations</span>**

CPAT Climate Policies Assessment Tool

EET Excise Taxes

EGT Energy Taxes

EVT Total Environmental Taxes

EXT Excise Taxes

GCS Public Consumption

GDP Growth Domestic Product

GIS Public Investment

HIC High-Income Countries

LIC Low-Income Countries

LMIC Lower Middle-Income Countries

MFMod Macro-Fiscal Model

PINE Policy Instruments for the Environment

PIT Personal Income Taxes

TRS Transfers

UMIC Upper Middle-Income Countries

VAT Sales Tax

## Introduction

Carbon pricing has effects on the baseline GDP growth forecasts. For the
reference projection of GDP growth, the user can choose between the
World Economic Outlook 2020, the World Economic Outlook 2021, and
manually entering the growth forecasts. CPAT adjusts these growth
forecasts endogenously depending on different carbon pricing and revenue
recycling scenarios. Two channels are captured: First, a carbon tax has
both direct and indirect effects on GDP. The latter arises when the
carbon tax revenues are recycled as a reduction of other taxes and/or as
an increase of government spending. These effects are quantified by the
fiscal multipliers. Second, the change in GDP affects energy consumption
and, therefore, the effective carbon tax revenues. This is captured by
the income elasticities of energy demand.

Regarding the first channel, an increase in carbon pricing and the
subsequent recycling of the carbon tax revenues into higher government
spending and/or lower taxes cause GDP to change with the direction and
magnitude depending on the respective spending and tax multipliers. For
the fiscal multipliers of energy excise taxes (EET), personal income
taxes (PIT), sales taxes (VAT), public investment (GIS), public
consumption (GCS), and transfers (TRS), CPAT provides four different
sources:

  - Income group
  - Global
  - Manual
  - Estimated

Multipliers indicate by how many % GDP responds on impact and in every
subsequent year up to a horizon of 10 years to an increase of a fiscal
policy instrument by 1% of GDP. The baseline multipliers can be adjusted
upwards and downwards by adding/subtracting one empirical standard
deviation. This acknowledges the uncertainty around empirical estimates
as well as the fact that multipliers tend to be higher during times of
economic contraction than expansion. It gives the CPAT user additional
flexibility in choosing the appropriate set of multipliers. The present
documentation reports the respective methodologies associated with each
multiplier source.

When applying fiscal multipliers in CPAT to estimate the GDP effects of
a carbon pricing scenario, the following caveats should be noted: First,
fiscal multipliers are a link output effects to policy changes in a
reduced from. The advantages are that many countries are covered and
that values are comparable between countries. Nevertheless, GDP effects
of policy interventions may depend on the state of the business cycle
and the design of the policy. These are details which multipliers
abstract from. Second, income group and global multipliers are derived
from an economic model which is empirically estimated. While the model
does not impose a strong prior on the multipliers, there is some small
remaining influence of the model assumptions on the multipliers.
Moreover, the values are averaged over countries because the
country-specific multipliers are very volatile. Finally, the estimated
multipliers also need to be interpreted with caution. While they are
based on a solid dataset and a state-of-the-art methodology, the dataset
only includes 75 countries with more than 10 observations. The results
have been averaged over various characteristics (see below for details)
and extrapolated to countries which are not covered by the data set.
Estimating country-specific multipliers is not feasible given the small
number of observations for each country.

## Income group specific multipliers

These multipliers have been extracted from the World Bank’s estimated
macro-structural model MFMod. Details on MFMod can be found in Burns et
al. (2019). The model is estimated for each country and country-specific
fiscal multipliers are then computed. To ensure robustness and reduce
volatility of multipliers across countries, they are averaged over the
countries of an income-group. This leads to four sets of multipliers:
One set each for high-income countries (HIC), upper middle-income
countries (UMIC), lower middle-income countries (LMIC), and low-income
countries (LIC).

MFMod also provides standard errors for these multiplier estimates which
are used to adjust the multipliers up- or downwards depending on user
preferences.

## Global multipliers

Like above, these multipliers have been extracted from the World Bank’s
estimated macro-structural model MFMod and are averaged variants of the
income group specific multipliers.

## Manual multipliers

The ‘Manual input tab’ allows the user to enter specific multiplier
values for the fiscal instruments mentioned above.

## Estimated multipliers

Estimated multipliers are obtained from a large panel of high-, middle-,
and low-income countries.

### Methodology for estimating dynamic multipliers using panel data

A thorough discussion of the underlying methodology is provided by
Schoder (2022) who exploits the global dataset to study how
environmental tax multipliers vary over the business cycle. To obtain
dynamic multiplier estimates we employ the local projection method
proposed by Jordà (2005) and extended to panel data by Jordà,
Schularick, and Taylor (2015) and Jordà, Schularick, and Taylor (2020).
As in Dabla-Norris and Lima (2018), we estimate for every horizon
$h = 0,1,\ldots,H - 1$,

$y_{i,t + h} - y_{i,t - 1} = \alpha_{i,h} + \delta_{t,h} + \text{Δs}_{i,t}\beta_{h} + \Delta x_{i,t}\gamma_{h} + \epsilon_{t,i,h}$

where $y_{i,t}$ is the dependent variable. We are interested in
explaining 100 times the log of real per-capita GDP in percent. Note
that we are estimating cumulative multipliers. Hence, for each horizon
we use the change of these variables relative to $t - 1$ as the
dependent variable. $s_{i,t}$ is the identified shock variable. For
each tax instrument considered, it is the cyclically adjusted tax
revenue-GDP ratio in percent. Hence, $\beta_{h}$ has the
interpretation of a cumulative multiplier. In particular, $\beta_{h}$
tells us, under the identifying assumption made and discussed below, by
how many percent(age-points) output (employment) increases in $t + h$
relative to $t - 1$ if discrete policy increases tax revenues by 1% of
GDP. $x_{i,t}$ is a vector of control variables. $\alpha_{i,h}$ and
$\delta_{t,h}$ are country and time fixed effects, respectively. To
account for heteroskedasticity and autocorrelation we apply the method
proposed by Driscoll and Kraay (1998) for estimating a robust covariance
matrix of parameters for a panel model. $\varepsilon_{t,i,h}$ is the
error term.

### Data set

To create the data set, we employ various sources: The OECD PINE data
set provides revenue data for total environmental taxes (EVT) and energy
taxes (EGT). From UNU WIDER, we take data on personal income taxes
(PIT), excise taxes (EXT), value added taxes (VAT), government
consumption (GCS), transfer payments (TRS), public investment (GIS).
Data on GDP, employment, GDP deflator, government spending, and
population are taken from the World Bank’s World Economic Indicators
database. We also use data on total final energy consumption, total
final diesel consumption, total final gasoline consumption, diesel and
gasoline supply prices, and implicit diesel and gasoline tax rates from
a data set compiled to inform CPAT. To remove outliers, we cut off the
1% and 99% percentiles of the changes in the tax revenue-GDP ratios.

### Cyclical adjustment of tax revenues and public spending

To address the simultaneous equation bias in the estimates of the tax
and spending multipliers which may arise from the feedback of output
into tax revenues and spending, we follow the *cyclical adjustment
approach* which assumes that there is a given instrument-specific
constant output gap elasticity which can be used to remove the cyclical
element from the tax revenues. For instance, the tax revenue-GDP ratios
$\frac{T}{Y}$ have been cyclically adjusted as

$\frac{T^{*}}{Y^{*}} = \frac{T}{Y}\left( \frac{Y^{*}}{Y} \right)^{\eta_{\text{YT}} - 1}$

where $Y^{*}$ is trend GDP obtained from the HP filter of log GDP and
$\eta_{\text{YT}}$ is the output gap elasticity of the tax revenues.
Price, Dang, and Botev (2015) estimated the latter, among other, for
PIT, VAT and indirect taxes for OECD countries and Dudine and Jalles
(2017) for a large sample of high and low-income countries. For
countries without elasticities available, we took the averages as the
best guess. Note, that there are no output gap elasticities available
for environmental taxes. Hence, for EGT, the output-gap elasticities are
estimated following the approach proposed by Price, Dang, and Botev
(2015) using total energy consumption as a proxy for the tax base. For
the spending instruments, the elasticities have been approximated by the
values estimated by Price, Dang, and Botev (2015).

### Estimation results

For each tax and spending instrument and for various subsamples, this
section presents the estimation results which, in the subsequent
section, are used to compute country-specific multipliers. Note that in
this section tax multipliers are *not* taken as the negative.

Estimates for the multipliers at horizons larger than eight are
restricted to zero when the standard errors become very large, and the
sign of the estimate contradicts economic theory. This is to reduce the
noise captured by the estimates for larger forecast horizons.

The following tables report the fiscal multipliers from the year of the
policy change until 10 years after. The multiplier for each horizon
indicates the percentage change of GDP (relative to the year before the
policy change) in response to a permanent increase in the policy
instrument by 1% of GDP.

#### Pooled panel

**GCS multipliers**

| Unit | H1   | H2   | H3   | H4   | H5   | H6  | H7   | H8   | H9  | H10  | H11  |
| ---- | ---- | ---- | ---- | ---- | ---- | --- | ---- | ---- | --- | ---- | ---- |
| ABW  | 0.72 | 1.06 | 0.91 | 0.76 | 0.58 | 0.4 | 0.05 | 0.03 | 0.1 | 0.12 | 0.09 |

**TRS multipliers**

| Unit | H1   | H2   | H3   | H4   | H5   | H6     | H7     | H8 | H9 | H10 | H11 |
| ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | -- | -- | --- | --- |
| ABW  | 0.66 | 0.72 | 0.63 | 0.55 | 0.28 | \-0.04 | \-0.28 | 0  | 0  | 0   | 0   |

**GIS multipliers**

| Unit | H1   | H2   | H3   | H4   | H5   | H6   | H7   | H8   | H9   | H10  | H11  |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| ABW  | 0.47 | 0.76 | 0.76 | 0.52 | 0.48 | 0.49 | 0.16 | 0.07 | 0.51 | 0.55 | 0.53 |

**PIT multipliers**

| Unit | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| ABW  | \-0.19 | \-0.57 | \-0.86 | \-1.26 | \-0.87 | \-0.77 | \-0.73 | \-0.94 | \-0.87 | \-0.71 | \-0.53 |

**EGT multipliers**

| Unit | H1     | H2     | H3     | H4    | H5     | H6     | H7     | H8     | H9     | H10 | H11 |
| ---- | ------ | ------ | ------ | ----- | ------ | ------ | ------ | ------ | ------ | --- | --- |
| ABW  | \-0.58 | \-0.76 | \-1.24 | \-0.5 | \-0.37 | \-0.64 | \-1.21 | \-0.77 | \-0.23 | 0   | 0   |

**EVT multipliers**

| Unit | H1     | H2     | H3     | H4     | H5   | H6 | H7    | H8     | H9   | H10 | H11 |
| ---- | ------ | ------ | ------ | ------ | ---- | -- | ----- | ------ | ---- | --- | --- |
| ABW  | \-0.75 | \-1.04 | \-0.84 | \-0.15 | 0.17 | 0  | \-0.4 | \-0.03 | 0.25 | 0   | 0   |

**EXT multipliers**

| Unit | H1     | H2     | H3     | H4    | H5     | H6   | H7     | H8     | H9 | H10 | H11 |
| ---- | ------ | ------ | ------ | ----- | ------ | ---- | ------ | ------ | -- | --- | --- |
| ABW  | \-0.24 | \-0.35 | \-0.17 | \-0.3 | \-0.26 | 0.01 | \-0.18 | \-0.15 | 0  | 0   | 0   |

**VAT multipliers**

| Unit | H1     | H2     | H3     | H4     | H5     | H6     | H7    | H8    | H9    | H10   | H11   |
| ---- | ------ | ------ | ------ | ------ | ------ | ------ | ----- | ----- | ----- | ----- | ----- |
| ABW  | \-0.47 | \-0.62 | \-0.32 | \-0.55 | \-0.83 | \-0.88 | \-1.1 | \-0.9 | \-0.9 | \-0.9 | \-0.9 |

### Income levels

**GCS multipliers**

| Unit       | H1   | H2   | H3   | H4   | H5   | H6   | H7     | H8     | H9     | H10    | H11    |
| ---------- | ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | 0.90 | 1.24 | 1.01 | 0.77 | 0.39 | 0.11 | \-0.26 | \-0.21 | \-0.24 | \-0.27 | \-0.32 |
| LIC & LMIC | 0.44 | 0.76 | 0.72 | 0.73 | 0.94 | 0.95 | 0.67   | 0.52   | 0.76   | 0.86   | 0.85   |

**TRS multipliers**

| Unit       | H1   | H2     | H3   | H4   | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ---- | ------ | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | 0.90 | 1.03   | 0.86 | 0.73 | 0.43   | 0.10   | \-0.12 | \-0.23 | \-0.34 | \-0.53 | \-0.78 |
| LIC & LMIC | 0.11 | \-0.02 | 0.10 | 0.12 | \-0.10 | \-0.38 | \-0.68 | \-0.60 | \-0.65 | \-0.89 | \-1.11 |

**GIS multipliers**

| Unit       | H1     | H2   | H3   | H4     | H5   | H6     | H7     | H8     | H9   | H10  | H11  |
| ---------- | ------ | ---- | ---- | ------ | ---- | ------ | ------ | ------ | ---- | ---- | ---- |
| HIC & UMIC | 0.81   | 1.22 | 1.07 | 0.97   | 0.78 | 0.84   | 0.42   | 0.23   | 0.66 | 0.66 | 0.49 |
| LIC & LMIC | \-0.03 | 0.06 | 0.28 | \-0.15 | 0.01 | \-0.10 | \-0.26 | \-0.19 | 0.23 | 0.36 | 0.60 |

**PIT multipliers**

| Unit       | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | \-0.22 | \-0.61 | \-0.90 | \-1.33 | \-0.79 | \-0.63 | \-0.74 | \-1.09 | \-1.07 | \-0.77 | \-0.63 |
| LIC & LMIC | 0.00   | \-0.30 | \-0.62 | \-0.74 | \-1.50 | \-1.79 | \-0.64 | 0.31   | 1.05   | \-0.04 | 0.64   |

**EGT multipliers**

| Unit       | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | \-0.85 | \-1.03 | \-1.24 | \-0.20 | 0.28   | 0.00   | \-0.83 | \-0.08 | 0.93   | 4.04   | 5.78   |
| LIC & LMIC | 0.23   | 0.03   | \-1.22 | \-1.46 | \-2.67 | \-2.87 | \-2.44 | \-3.12 | \-4.27 | \-3.72 | \-3.14 |

**EVT multipliers**

| Unit       | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | \-1.04 | \-1.06 | \-0.72 | 0.22   | 0.91   | 0.76   | 0.21   | 0.55   | 1.46   | 3.28   | 4.68   |
| LIC & LMIC | 0.47   | \-0.97 | \-1.39 | \-1.72 | \-3.01 | \-3.43 | \-3.03 | \-2.57 | \-5.32 | \-4.47 | \-3.79 |

**EXT multipliers**

| Unit       | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | \-0.28 | \-0.46 | \-0.28 | \-0.33 | \-0.71 | \-0.44 | 0.05   | 0.22   | 0.74   | 1.47   | 1.91   |
| LIC & LMIC | \-0.19 | \-0.15 | 0.02   | \-0.23 | 0.66   | 0.95   | \-0.65 | \-0.93 | \-1.48 | \-1.97 | \-1.12 |

**VAT multipliers**

| Unit       | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ---------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| HIC & UMIC | \-0.42 | \-0.37 | \-0.02 | 0.02   | 0.20   | 0.05   | \-0.29 | \-0.64 | \-1.12 | \-1.47 | \-1.49 |
| LIC & LMIC | \-0.58 | \-1.07 | \-0.86 | \-1.62 | \-2.76 | \-2.66 | \-2.65 | \-2.70 | \-2.60 | \-3.13 | \-3.76 |

### Regions

**GCS multipliers**

| Unit                           | H1   | H2   | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 1.52 | 1.76 | 1.35   | 1.32   | 1.10   | 0.94   | 0.63   | 0.92   | 1.42   | 1.08   | 0.79   |
| South East Asia & Pacific      | 0.67 | 1.08 | 1.01   | 1.06   | 1.11   | 1.36   | 0.85   | 0.78   | 0.67   | 1.18   | 1.04   |
| Africa                         | 0.25 | 0.29 | \-0.07 | \-0.50 | \-0.43 | \-1.12 | \-0.94 | \-0.90 | \-0.99 | \-0.54 | \-0.56 |
| Eastern Europe                 | 0.68 | 1.43 | 1.30   | 0.89   | 0.64   | 0.40   | \-0.07 | 0.16   | 0.39   | 0.14   | 0.16   |
| Central Asia & Middle East     | 1.58 | 1.80 | 1.58   | 1.77   | 1.30   | 0.95   | 0.48   | 0.27   | 0.54   | \-0.11 | 0.35   |
| Western Europe & North America | 0.32 | 0.53 | 0.58   | 0.24   | \-0.14 | \-0.32 | \-0.69 | \-0.96 | \-1.00 | \-1.09 | \-1.26 |

**TRS multipliers**

| Unit                           | H1   | H2   | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 0.79 | 0.92 | 0.72   | 0.66   | 0.56   | 0.25   | \-0.04 | \-0.05 | \-0.18 | \-0.53 | \-0.67 |
| South East Asia & Pacific      | 0.81 | 0.97 | 1.12   | 1.27   | 0.83   | 0.38   | 0.08   | \-0.44 | \-0.33 | \-0.33 | \-0.23 |
| Africa                         | 0.09 | 0.00 | \-0.04 | \-0.35 | \-0.53 | \-0.96 | \-1.26 | \-1.21 | \-1.21 | \-1.55 | \-1.69 |
| Eastern Europe                 | 0.85 | 0.83 | 0.58   | 0.50   | 0.25   | 0.15   | \-0.08 | \-0.05 | \-0.39 | \-0.50 | \-1.03 |
| Central Asia & Middle East     | 0.47 | 0.72 | 0.92   | 1.03   | 1.13   | 1.08   | 0.98   | 1.14   | 1.27   | 0.95   | 0.35   |
| Western Europe & North America | 0.70 | 0.67 | 0.43   | 0.00   | \-0.68 | \-1.40 | \-1.64 | \-1.76 | \-1.78 | \-2.05 | \-1.87 |

**GIS multipliers**

| Unit                           | H1   | H2   | H3   | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ---- | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 0.44 | 0.60 | 0.36 | 0.22   | 0.06   | 0.38   | 0.63   | 0.25   | 0.36   | 0.36   | 0.81   |
| South East Asia & Pacific      | 0.35 | 0.39 | 0.33 | 0.14   | 0.18   | 0.16   | \-0.71 | \-0.48 | 0.59   | 1.04   | 1.07   |
| Africa                         | 0.13 | 0.42 | 0.88 | \-0.15 | \-0.15 | \-0.35 | \-0.57 | \-0.28 | \-0.15 | \-0.25 | \-0.36 |
| Eastern Europe                 | 0.93 | 1.61 | 1.40 | 1.26   | 1.13   | 1.23   | 0.83   | 0.32   | 0.40   | 0.28   | \-0.48 |
| Central Asia & Middle East     | 0.84 | 1.71 | 1.73 | 1.88   | 1.98   | 1.71   | 1.44   | 0.95   | 1.53   | 1.16   | 1.55   |
| Western Europe & North America | 0.43 | 0.52 | 0.52 | 0.63   | 0.63   | 0.57   | 0.53   | 0.39   | 0.34   | 0.32   | 0.12   |

**PIT multipliers**

| Unit                           | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 1.20   | 1.43   | 1.30   | \-0.09 | \-0.08 | \-0.07 | \-0.92 | \-1.05 | \-1.23 | \-2.08 | \-0.99 |
| South East Asia & Pacific      | \-0.69 | \-1.05 | \-0.76 | \-1.55 | \-1.48 | \-1.68 | \-1.78 | \-2.06 | \-1.95 | \-1.91 | \-1.01 |
| Africa                         | \-0.53 | \-0.40 | 0.08   | \-0.32 | \-1.44 | \-1.39 | \-0.66 | \-1.34 | \-0.92 | \-1.35 | \-2.42 |
| Eastern Europe                 | 0.16   | \-1.65 | \-3.27 | \-4.30 | \-3.67 | \-3.78 | \-4.12 | \-4.24 | \-2.78 | \-1.10 | \-1.82 |
| Central Asia & Middle East     | \-1.42 | \-3.05 | \-4.38 | \-6.20 | \-6.64 | \-6.78 | \-6.36 | \-5.23 | \-5.08 | \-5.01 | \-5.59 |
| Western Europe & North America | \-0.18 | \-0.23 | \-0.33 | 0.05   | 1.04   | 1.34   | 1.51   | 1.07   | 0.79   | 0.76   | 1.12   |

**EGT multipliers**

| Unit                           | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 0.37   | 0.53   | \-0.58 | \-0.43 | \-2.44 | \-5.66 | \-8.87 | \-7.66 | \-7.57 | \-5.90 | \-2.52 |
| South East Asia & Pacific      | 0.46   | 0.19   | \-0.45 | \-0.34 | 0.21   | \-1.01 | \-2.00 | \-0.20 | \-3.51 | \-3.22 | \-6.00 |
| Africa                         | \-0.09 | 0.29   | \-0.93 | \-1.40 | \-2.41 | \-1.98 | \-1.26 | \-2.11 | \-3.15 | \-0.25 | 1.23   |
| Eastern Europe                 | \-0.82 | \-0.86 | 0.59   | 2.80   | 4.96   | 7.35   | 6.74   | 6.85   | 7.85   | 11.15  | 13.64  |
| Central Asia & Middle East     | 1.17   | 3.98   | 2.31   | 3.77   | 2.51   | \-2.06 | \-3.98 | \-7.78 | \-5.14 | \-4.77 | \-4.25 |
| Western Europe & North America | \-2.06 | \-4.91 | \-6.36 | \-7.42 | \-8.73 | \-9.23 | \-8.95 | \-7.28 | \-6.08 | \-3.91 | \-3.83 |

**EVT multipliers**

| Unit                           | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 0.10   | 0.07   | \-0.67 | \-0.09 | \-1.45 | \-4.15 | \-6.28 | \-4.81 | \-4.63 | \-3.05 | \-0.54 |
| South East Asia & Pacific      | 0.95   | 0.34   | \-0.19 | \-0.56 | \-0.10 | \-0.41 | \-0.15 | 1.09   | \-1.16 | \-0.86 | \-2.39 |
| Africa                         | \-0.45 | \-1.79 | \-1.88 | \-2.90 | \-3.84 | \-3.17 | \-2.70 | \-1.59 | \-3.20 | \-0.94 | 0.50   |
| Eastern Europe                 | \-2.40 | \-2.95 | \-1.95 | 0.25   | 2.46   | 4.57   | 4.66   | 4.30   | 4.71   | 7.43   | 10.25  |
| Central Asia & Middle East     | 1.07   | 2.66   | 1.63   | 2.60   | 2.07   | \-1.06 | \-2.03 | \-4.23 | \-2.53 | \-2.95 | \-1.58 |
| Western Europe & North America | \-0.80 | \-1.04 | \-0.04 | 0.14   | 0.70   | 0.55   | \-0.13 | 0.53   | 1.83   | 2.77   | 1.96   |

**EXT multipliers**

| Unit                           | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | \-0.38 | \-1.43 | \-2.25 | \-2.60 | \-3.71 | \-4.68 | \-5.55 | \-7.38 | \-7.90 | \-7.45 | \-7.57 |
| South East Asia & Pacific      | 0.75   | 0.58   | 0.94   | 1.05   | 0.53   | 0.72   | \-0.24 | 0.50   | 0.02   | 0.32   | 0.49   |
| Africa                         | 0.34   | 0.13   | 0.31   | \-0.14 | 1.38   | 1.00   | \-0.08 | \-0.46 | \-0.86 | \-1.08 | \-0.72 |
| Eastern Europe                 | \-0.82 | \-0.68 | 0.38   | 1.01   | 0.91   | 2.21   | 2.58   | 3.17   | 3.37   | 4.74   | 7.06   |
| Central Asia & Middle East     | 0.20   | 1.03   | \-0.27 | \-1.70 | \-3.70 | \-3.50 | \-3.08 | \-3.30 | \-3.16 | \-3.80 | \-2.43 |
| Western Europe & North America | \-1.06 | \-1.22 | \-0.78 | \-0.67 | 0.28   | 0.84   | 1.34   | 1.79   | 2.83   | 3.32   | 3.29   |

**VAT multipliers**

| Unit                           | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------------------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Latin America & Caribbean      | 0.44   | 1.03   | 1.78   | 2.05   | 1.71   | 0.66   | 0.50   | 0.76   | 0.58   | \-0.34 | 0.20   |
| South East Asia & Pacific      | 0.48   | 0.06   | \-0.59 | \-0.96 | \-1.39 | \-2.00 | \-1.35 | \-1.14 | \-1.72 | \-2.49 | \-3.01 |
| Africa                         | \-0.41 | \-0.32 | 0.39   | \-0.41 | \-0.47 | \-0.66 | \-1.35 | \-1.08 | \-1.59 | \-1.09 | \-1.35 |
| Eastern Europe                 | \-0.78 | \-1.07 | \-0.60 | \-1.00 | \-1.89 | \-1.82 | \-1.97 | \-2.72 | \-2.72 | \-3.56 | \-3.95 |
| Central Asia & Middle East     | \-0.97 | \-1.98 | \-3.32 | \-3.53 | \-2.75 | \-0.97 | \-1.21 | \-1.32 | \-2.21 | \-2.86 | \-4.59 |
| Western Europe & North America | \-0.64 | \-0.64 | \-0.10 | 0.00   | 0.10   | \-0.14 | \-0.51 | \-0.93 | \-1.19 | \-1.28 | \-1.20 |

### Debt levels

**GCS multipliers**

| Unit      | H1   | H2   | H3   | H4   | H5   | H6   | H7     | H8     | H9     | H10  | H11  |
| --------- | ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ---- | ---- |
| Low debt  | 0.81 | 1.14 | 1.09 | 0.92 | 0.53 | 0.30 | 0.11   | 0.10   | 0.12   | 0.11 | 0.08 |
| High debt | 0.59 | 0.92 | 0.68 | 0.52 | 0.61 | 0.39 | \-0.02 | \-0.12 | \-0.04 | 0.09 | 0.21 |

**TRS multipliers**

| Unit      | H1   | H2   | H3   | H4   | H5   | H6     | H7     | H8     | H9     | H10    | H11    |
| --------- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ |
| Low debt  | 0.76 | 0.75 | 0.68 | 0.59 | 0.45 | 0.28   | 0.12   | 0.15   | \-0.07 | \-0.18 | \-0.50 |
| High debt | 0.52 | 0.70 | 0.57 | 0.49 | 0.17 | \-0.18 | \-0.54 | \-0.67 | \-0.68 | \-1.08 | \-1.27 |

**GIS multipliers**

| Unit      | H1   | H2   | H3   | H4   | H5   | H6   | H7     | H8     | H9   | H10  | H11  |
| --------- | ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ---- | ---- | ---- |
| Low debt  | 0.74 | 1.09 | 0.76 | 0.57 | 0.63 | 0.69 | 0.43   | 0.10   | 0.36 | 0.37 | 0.29 |
| High debt | 0.18 | 0.31 | 0.62 | 0.29 | 0.28 | 0.12 | \-0.10 | \-0.05 | 0.38 | 0.42 | 0.54 |

**PIT multipliers**

| Unit      | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| --------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Low debt  | \-0.10 | \-0.63 | \-1.00 | \-1.56 | \-1.27 | \-1.12 | \-1.10 | \-1.19 | \-1.02 | \-0.92 | \-1.01 |
| High debt | \-0.57 | \-0.44 | \-0.43 | \-0.31 | 0.64   | 0.69   | 0.79   | 0.06   | \-0.07 | 0.66   | 1.84   |

**EGT multipliers**

| Unit      | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10  | H11  |
| --------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ---- | ---- |
| Low debt  | \-0.61 | \-0.38 | \-0.52 | 0.26   | 0.54   | \-0.23 | \-1.06 | \-0.46 | 0.41   | 3.70 | 5.69 |
| High debt | \-0.84 | \-1.94 | \-3.11 | \-2.47 | \-2.32 | \-0.68 | \-0.51 | \-0.47 | \-0.40 | 0.63 | 0.49 |

**EVT multipliers**

| Unit      | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9   | H10  | H11  |
| --------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ---- | ---- | ---- |
| Low debt  | \-0.75 | \-0.56 | \-0.37 | 0.48   | 0.50   | \-0.18 | \-0.69 | \-0.52 | 0.03 | 2.45 | 4.39 |
| High debt | \-0.95 | \-2.45 | \-2.17 | \-1.93 | \-0.49 | 1.10   | 0.98   | 1.74   | 1.75 | 2.10 | 1.46 |

**EXT multipliers**

| Unit      | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11   |
| --------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ----- |
| Low debt  | \-0.05 | \-0.06 | 0.30   | 0.16   | \-0.55 | \-0.28 | \-0.18 | 0.11   | 0.51   | 0.95   | 1.7   |
| High debt | \-0.74 | \-1.13 | \-1.24 | \-1.49 | \-0.03 | 0.44   | \-0.10 | \-0.68 | \-0.97 | \-0.78 | \-0.2 |

**VAT multipliers**

| Unit      | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| --------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Low debt  | \-0.54 | \-0.81 | \-0.63 | \-0.98 | \-1.35 | \-1.27 | \-1.54 | \-1.86 | \-2.16 | \-2.68 | \-2.86 |
| High debt | \-0.53 | \-0.39 | 0.37   | 0.33   | 0.16   | \-0.17 | \-0.23 | \-0.33 | \-0.57 | \-0.83 | \-1.03 |

### Trade openness

**GCS multipliers**

| Unit         | H1   | H2   | H3   | H4   | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | 0.79 | 1.25 | 1.16 | 0.99 | 0.92   | 1.03   | 0.83   | 0.87   | 0.93   | 0.87   | 0.88   |
| Low imports  | 0.62 | 0.78 | 0.54 | 0.32 | \-0.03 | \-0.54 | \-1.16 | \-1.24 | \-1.11 | \-1.01 | \-1.02 |

**TRS multipliers**

| Unit         | H1   | H2   | H3   | H4   | H5   | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | 0.74 | 0.72 | 0.69 | 0.61 | 0.20 | \-0.19 | \-0.42 | \-0.53 | \-0.54 | \-0.63 | \-1.06 |
| Low imports  | 0.55 | 0.69 | 0.54 | 0.46 | 0.32 | 0.12   | \-0.13 | \-0.11 | \-0.32 | \-0.65 | \-0.71 |

**GIS multipliers**

| Unit         | H1   | H2   | H3   | H4   | H5   | H6   | H7     | H8     | H9   | H10  | H11  |
| ------------ | ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ---- | ---- | ---- |
| High imports | 0.42 | 0.74 | 0.61 | 0.52 | 0.41 | 0.33 | \-0.14 | \-0.13 | 0.34 | 0.39 | 0.30 |
| Low imports  | 0.58 | 0.81 | 1.07 | 0.54 | 0.65 | 0.78 | 0.66   | 0.42   | 0.82 | 0.88 | 0.97 |

**PIT multipliers**

| Unit         | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | \-0.73 | \-1.66 | \-2.55 | \-2.61 | \-1.70 | \-1.89 | \-1.61 | \-3.13 | \-3.19 | \-1.68 | \-1.98 |
| Low imports  | 0.04   | \-0.09 | \-0.16 | \-0.67 | \-0.52 | \-0.28 | \-0.35 | \-0.06 | 0.03   | \-0.33 | 0.00   |

**EGT multipliers**

| Unit         | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | 0.86   | 0.88   | 1.20   | 3.04   | 5.22   | 6.43   | 7.25   | 8.76   | 10.49  | 13.98  | 15.78  |
| Low imports  | \-1.09 | \-1.35 | \-2.12 | \-1.81 | \-2.45 | \-3.37 | \-4.58 | \-4.57 | \-4.61 | \-2.58 | \-0.98 |

**EVT multipliers**

| Unit         | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11  |
| ------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ---- |
| High imports | \-1.32 | \-1.56 | \-0.85 | 0.81   | 3.54   | 4.59   | 4.96   | 5.27   | 5.81   | 7.63   | 9.07 |
| Low imports  | \-0.51 | \-0.83 | \-0.84 | \-0.55 | \-1.22 | \-1.94 | \-2.71 | \-2.33 | \-2.21 | \-0.67 | 0.66 |

**EXT multipliers**

| Unit         | H1     | H2     | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | \-0.60 | \-0.23 | 0.28   | 0.20   | 0.46   | 0.98   | 1.70   | 2.65   | 2.88   | 3.81   | 4.97   |
| Low imports  | \-0.03 | \-0.41 | \-0.43 | \-0.58 | \-0.67 | \-0.54 | \-1.23 | \-1.72 | \-1.53 | \-1.48 | \-1.09 |

**VAT multipliers**

| Unit         | H1     | H2    | H3     | H4     | H5     | H6     | H7     | H8     | H9     | H10    | H11    |
| ------------ | ------ | ----- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| High imports | \-0.50 | \-0.9 | \-0.66 | \-1.21 | \-1.97 | \-2.02 | \-2.28 | \-2.58 | \-2.66 | \-3.06 | \-3.47 |
| Low imports  | \-0.45 | \-0.4 | \-0.05 | \-0.04 | 0.05   | \-0.04 | \-0.25 | \-0.48 | \-0.92 | \-1.35 | \-1.49 |

### Computation of country specific dynamic multipliers

In the final step, the raw multipliers for the pooled panel and various
subsamples which are reported above are processed to compute
country-specific dynamic multipliers for up to 10 years ahead. To obtain
country-specific multipliers, we take a weighted average over the
respective multipliers from each sample/subsample which the country is
part of.

The construction of the weights follows this reasoning: The effective
sample size decreases with the length of the estimation horizon. Hence,
the longer the multiplier horizon, the more likely the estimate is
blurred by noise. This is especially true for the sub-samples as they
have fewer observations than the full sample in the first place. To
account for this, the weights for the contribution to the multiplier
average of the pooled estimates start from zero but increase linearly
with the multiplier horizon.

Since, the multipliers for the spending categories (GCS, GIS, TRS) are
not very volatile across horizons or across subsamples (especially at
short horizons), we assign relatively more weight to the subsamples
compared to the panel. The remaining four categories (income levels,
region, debt level, trade openness) have equal weights:

**Weights for the contribution to the multiplier average of the pooled
estimates**

| Unit    | H1 | H2    | H3    | H4   | H5    | H6    | H7  | H8    | H9    | H10  | H11   |
| ------- | -- | ----- | ----- | ---- | ----- | ----- | --- | ----- | ----- | ---- | ----- |
| Weights | 0  | 0.083 | 0.166 | 0.25 | 0.333 | 0.416 | 0.5 | 0.583 | 0.666 | 0.75 | 0.833 |

**Weights for the contribution to the multiplier average of the income
level, region, debt level or trade openness estimates**

| Unit    | H1   | H2    | H3    | H4    | H5    | H6    | H7    | H8    | H9    | H10   | H11   |
| ------- | ---- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Weights | 0.25 | 0.229 | 0.208 | 0.187 | 0.166 | 0.145 | 0.125 | 0.104 | 0.083 | 0.062 | 0.041 |

The weights for PIT and VAT multipliers are:

**Weights for the contribution to the multiplier average of the pooled
estimates**

| Unit    | H1  | H2    | H3    | H4    | H5    | H6    | H7   | H8    | H9    | H10   | H11   |
| ------- | --- | ----- | ----- | ----- | ----- | ----- | ---- | ----- | ----- | ----- | ----- |
| Weights | 0.5 | 0.541 | 0.583 | 0.625 | 0.666 | 0.708 | 0.75 | 0.791 | 0.833 | 0.875 | 0.916 |

**Weights for the contribution to the multiplier average of the income
level, region, debt level or trade openness estimates**

| Unit    | H1    | H2    | H3    | H4    | H5    | H6    | H7    | H8    | H9    | H10   | H11   |
| ------- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Weights | 0.125 | 0.114 | 0.104 | 0.093 | 0.083 | 0.072 | 0.062 | 0.052 | 0.041 | 0.031 | 0.020 |

EGT multipliers are very volatile across horizons and subsamples. Hence,
we assign a higher weight to the pooled results:

**Weights for the contribution to the multiplier average of the pooled
estimates**

| Unit    | H1  | H2    | H3    | H4   | H5    | H6    | H7  | H8    | H9    | H10  | H11   |
| ------- | --- | ----- | ----- | ---- | ----- | ----- | --- | ----- | ----- | ---- | ----- |
| Weights | 0.8 | 0.816 | 0.833 | 0.85 | 0.866 | 0.883 | 0.9 | 0.916 | 0.933 | 0.95 | 0.966 |

**Weights for the contribution to the multiplier average of the income
level, region, debt level or trade openness estimates**

| Unit    | H1   | H2    | H3    | H4    | H5    | H6    | H7    | H8    | H9    | H10   | H11   |
| ------- | ---- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Weights | 0.05 | 0.045 | 0.041 | 0.037 | 0.033 | 0.029 | 0.025 | 0.020 | 0.016 | 0.012 | 0.008 |

The weights for EVT and EXT multipliers are:

**Weights for the contribution to the multiplier average of the pooled
estimates**

| Unit    | H1   | H2    | H3    | H4    | H5    | H6    | H7    | H8    | H9    | H10   | H11   |
| ------- | ---- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Weights | 0.75 | 0.771 | 0.791 | 0.812 | 0.833 | 0.854 | 0.875 | 0.895 | 0.916 | 0.937 | 0.958 |

**Weights for the contribution to the multiplier average of the income
level, region, debt level or trade openness estimates**

| Unit    | H1    | H2    | H3    | H4    | H5    | H6    | H7    | H8    | H9    | H10   | H11   |
| ------- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| Weights | 0.062 | 0.057 | 0.052 | 0.046 | 0.041 | 0.036 | 0.031 | 0.026 | 0.020 | 0.015 | 0.010 |

Finally, the energy excise tax multipliers are approximated by the means
of the EGT and EVT multipliers.

## References

1.  Burns, Andrew, Benoit Campagne, Charl Jooste, David Stephan, Thi
    Thanh Bui. 2019. “The World Bank Macro-Fiscal Model Technical
    Description.” World Bank Working Paper 8965.

2.  Dabla-Norris, Era, and Frederico Lima. 2018. “Macroeconomic Effects
    of Tax Rate and Base Changes: Evidence from Fiscal Consolidations.”
    IMF Working Papers 18/220. International Monetary Fund.

3.  Driscoll, John C., and Aart C. Kraay. 1998. “Consistent Covariance
    Matrix Estimation with Spatially Dependent Panel Data.” The Review
    of Economics and Statistics 80 (4): 549–60.

4.  Dudine, Paolo, and João Tovar Jalles. 2017. “How Buoyant is the Tax
    System? New Evidence from a Large Heterogeneous Panel.” IMF Working
    Papers 2017/004. International Monetary Fund.

5.  Jordà, Òscar. 2005. “Estimation and Inference of Impulse Responses
    by Local Projections.” American Economic Review 95 (1): 161–82.

6.  Jordà, Òscar, Moritz Schularick, and Alan M. Taylor. 2015. “Betting
    the house.” Journal of International Economics 96 (S1): 2–18.

7.  Jordà, Òscar, Moritz Schularick, and Alan M. Taylor. 2020. “The
    effects of quasi-random monetary experiments.” Journal of Monetary
    Economics 112 (C):22–40.

8.  Price, Robert, Thai-Thanh Dang, and Jarmila Botev. 2015. “Adjusting
    fiscal balances for the business cycle: New tax and expenditure
    elasticity estimates for OECD countries.” OECD Economics Department
    Working Papers 1275.

9.  Schoder, Christian. 2022. “Regime-Dependent Environmental Tax
    Multipliers: Evidence from 75 countries.” Journal of Environmental
    Economics and Policy, forthcoming, 2022.
    https://doi.org/10.1080/21606544.2022.2089238
