
# **Cover** {.unnumbered}

<p>Technical notes, August 26<sup>th</sup>, 2022</p>

## **Foreword** {.unnumbered}

### **Why carbon pricing?** {.unnumbered}

Climate change is one of the greatest development challenges of our time. To stay below 2°C of global warming, the world will need to reach net zero emissions by the end of this century. That means we must act now, and carbon pricing is an essential part of the solution.

A price on carbon is intended to capture externality costs of carbon emissions. Examples include damage to infrastructure from floods, loss of crops from droughts, ecosystem degradation from increasing rainfall variability, or health care costs from heat waves. Putting a price on carbon would help shift the burden for the damage back to those who are responsible for it and, importantly, those who can act to reduce it.

Carbon pricing is a cost-effective tool to lower emissions, but well-designed reforms can have several benefits beyond emissions reductions. This is true especially in low-income countries where revenues can help finance vital government services. Other development co-benefits include improvements in human health due to the co-emission of carbon emissions and local pollutants, and reductions in congestion and traffic-related accidents, for example as a result of a modal shift from private vehicles to public transit or soft modes.

### **What is the Climate Policy Assessment Tool?** {.unnumbered}

The Climate Policy Assessment Tool (CPAT) was developed to help countries provide a rapid evaluation of the potential impacts of carbon pricing reforms. As a global tool covering more than 150 countries, CPAT can be used as a one-stop-shop by anyone who is interested in a quick diagnostic of the potential benefits of a carbon price reform across multiple key dimensions, including not only emissions reduction potential and macroeconomic aggregates but also air pollution and health, road fatalities and congestion, and distributional impacts.

## **Why 400 pages of documentation?** {.unnumbered}

CPAT is comprised of several economic models. Economic models describe a simplified reality and so they are, by definition, subject to considerable uncertainty. When interpreting the results of a model, knowing the underlying assumptions is critical. For this reason, several steps have been taken to improve the transparency of CPAT. First, the tool is spreadsheet-based with data and formulas readily accessible within the tool. Second, the tool is accompanied by a detailed 400-page documentation of the methodology which includes important caveats and cautions related to interpretation and data issues.

CPAT is designed to be a global public good. In a constantly evolving world, the tool will need continuous updating and upgrading. By putting together and releasing the detailed CPAT methodology, it is our hope that any interested party can adapt the tool for their own needs and contribute to its further development.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
